# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# Matikan Configuration Cache biar gak serialization error di CI
org.gradle.configuration-cache=false

# Enable Parallel Build & Caching biasa
org.gradle.parallel=true
org.gradle.caching=true
