name: Rilis Otomatis APK Vanz Music

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode dari Repositori
      uses: actions/checkout@v4

    - name: Set up JDK 17 (Mesin Java)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Berikan Izin Akses Gradle
      run: chmod +x gradlew

    - name: Rakit APK Tanpa Beban PC Lokal
      run: ./gradlew assembleDebug

    - name: Simpan dan Upload Hasil APK Jadi
      uses: actions/upload-artifact@v4
      with:
        name: Vanz-Music-App-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
